/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_teoria1;

/**
 *
 * @author User
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jd_Mcreacion = new javax.swing.JDialog();
        Crear_Planta = new javax.swing.JButton();
        Crear_proveedor = new javax.swing.JButton();
        Crear_conse = new javax.swing.JButton();
        Crear_cliente = new javax.swing.JButton();
        Crear_compa = new javax.swing.JButton();
        lb_fondocreacion = new javax.swing.JLabel();
        Jd_Mmodificacion = new javax.swing.JDialog();
        Jd_Meliminacion = new javax.swing.JDialog();
        C_Compañia = new javax.swing.JDialog();
        C_Planta = new javax.swing.JDialog();
        C_Proveedor = new javax.swing.JDialog();
        C_Conse = new javax.swing.JDialog();
        C_Cliente = new javax.swing.JDialog();
        Bt_Menu_Creacion = new javax.swing.JButton();
        Bt_Menu_Modificar = new javax.swing.JButton();
        Bt_Menu_Eliminacion = new javax.swing.JButton();
        lb_fondo1 = new javax.swing.JLabel();

        Jd_Mcreacion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Crear_Planta.setText("Planta");
        Jd_Mcreacion.getContentPane().add(Crear_Planta, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 110, -1));

        Crear_proveedor.setText("Proveedor");
        Jd_Mcreacion.getContentPane().add(Crear_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 110, -1));

        Crear_conse.setText("Consecionario");
        Jd_Mcreacion.getContentPane().add(Crear_conse, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, -1));

        Crear_cliente.setText("Cliente");
        Jd_Mcreacion.getContentPane().add(Crear_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 110, -1));

        Crear_compa.setText("Compañia");
        Jd_Mcreacion.getContentPane().add(Crear_compa, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 110, -1));

        lb_fondocreacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diseno-fondo-moderno-blanco-3d_53876-88246.jpg"))); // NOI18N
        Jd_Mcreacion.getContentPane().add(lb_fondocreacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout Jd_MmodificacionLayout = new javax.swing.GroupLayout(Jd_Mmodificacion.getContentPane());
        Jd_Mmodificacion.getContentPane().setLayout(Jd_MmodificacionLayout);
        Jd_MmodificacionLayout.setHorizontalGroup(
            Jd_MmodificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        Jd_MmodificacionLayout.setVerticalGroup(
            Jd_MmodificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Jd_MeliminacionLayout = new javax.swing.GroupLayout(Jd_Meliminacion.getContentPane());
        Jd_Meliminacion.getContentPane().setLayout(Jd_MeliminacionLayout);
        Jd_MeliminacionLayout.setHorizontalGroup(
            Jd_MeliminacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        Jd_MeliminacionLayout.setVerticalGroup(
            Jd_MeliminacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout C_CompañiaLayout = new javax.swing.GroupLayout(C_Compañia.getContentPane());
        C_Compañia.getContentPane().setLayout(C_CompañiaLayout);
        C_CompañiaLayout.setHorizontalGroup(
            C_CompañiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        C_CompañiaLayout.setVerticalGroup(
            C_CompañiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout C_PlantaLayout = new javax.swing.GroupLayout(C_Planta.getContentPane());
        C_Planta.getContentPane().setLayout(C_PlantaLayout);
        C_PlantaLayout.setHorizontalGroup(
            C_PlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        C_PlantaLayout.setVerticalGroup(
            C_PlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout C_ProveedorLayout = new javax.swing.GroupLayout(C_Proveedor.getContentPane());
        C_Proveedor.getContentPane().setLayout(C_ProveedorLayout);
        C_ProveedorLayout.setHorizontalGroup(
            C_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        C_ProveedorLayout.setVerticalGroup(
            C_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout C_ConseLayout = new javax.swing.GroupLayout(C_Conse.getContentPane());
        C_Conse.getContentPane().setLayout(C_ConseLayout);
        C_ConseLayout.setHorizontalGroup(
            C_ConseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        C_ConseLayout.setVerticalGroup(
            C_ConseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout C_ClienteLayout = new javax.swing.GroupLayout(C_Cliente.getContentPane());
        C_Cliente.getContentPane().setLayout(C_ClienteLayout);
        C_ClienteLayout.setHorizontalGroup(
            C_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        C_ClienteLayout.setVerticalGroup(
            C_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bt_Menu_Creacion.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        Bt_Menu_Creacion.setText("Creacion");
        getContentPane().add(Bt_Menu_Creacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, 230, 50));

        Bt_Menu_Modificar.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        Bt_Menu_Modificar.setText("Modificar");
        getContentPane().add(Bt_Menu_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, 30));

        Bt_Menu_Eliminacion.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        Bt_Menu_Eliminacion.setText("Eliminar");
        getContentPane().add(Bt_Menu_Eliminacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, -1, -1));

        lb_fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/WhatsApp Image 2020-03-05 at 6.43.00 PM.jpeg"))); // NOI18N
        getContentPane().add(lb_fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 980, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Menu_Creacion;
    private javax.swing.JButton Bt_Menu_Eliminacion;
    private javax.swing.JButton Bt_Menu_Modificar;
    private javax.swing.JDialog C_Cliente;
    private javax.swing.JDialog C_Compañia;
    private javax.swing.JDialog C_Conse;
    private javax.swing.JDialog C_Planta;
    private javax.swing.JDialog C_Proveedor;
    private javax.swing.JButton Crear_Planta;
    private javax.swing.JButton Crear_cliente;
    private javax.swing.JButton Crear_compa;
    private javax.swing.JButton Crear_conse;
    private javax.swing.JButton Crear_proveedor;
    private javax.swing.JDialog Jd_Mcreacion;
    private javax.swing.JDialog Jd_Meliminacion;
    private javax.swing.JDialog Jd_Mmodificacion;
    private javax.swing.JLabel lb_fondo1;
    private javax.swing.JLabel lb_fondocreacion;
    // End of variables declaration//GEN-END:variables
}
